name: docker build action
description: 
inputs:
  username:
    description: "docker username"
    required: true
  image_name:
    description: "image name"
    required: true
  tag_name:
    description: "tag name"
    required: false
    default: "latest"
runs:
  using: composite
  steps:
  - run: |
      docker tag ${{inputs.imagename}} ${{inputs.tag_name}}
      docker push ${{inputs.imagename}}:${{inputs.tag_name}} ${{inputs.username}}/${{inputs.image_name}}
    shell: bash