name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      uses: brunogcmf/academy/.github/actions/docker_build@main
      with:
        path_dockerfile: Dockerfile
        image_name: cicd-exercise-2
        tag_name: latest

    - name: List Docker images
      run: docker image list